[tool.black]
exclude = ["custom_speech_recognition"]

[tool.ruff]
select = [
    # "E", # pycodestyle
    "F", # pyflakes
    "I", # isort
    "UP", # pyupgrade
]
src = ["."]
exclude = ["custom_speech_recognition"]
